services:
  grist:
    image: gristlabs/grist-oss
    ports:
      - "8484:8484"
    volumes:
      - ${PERSIST_DIR}:/persist 
    env_file:
      # This points to your .env file relative to the docker-compose.yml file.
      - .env
    stdin_open: true 
    tty: true