#!/usr/bin/env bash

RUN_DIR="$(pwd)"
SCRIPT_FILE="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_FILE")"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
export PERSIST_DIR="$PROJECT_DIR/persist"
cd "$PROJECT_DIR"

docker compose down

cd "$RUN_DIR"