#!/usr/bin/env bash

SCRIPT_FILE="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_FILE")"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
export PERSIST_DIR="$PROJECT_DIR/persist"

docker run                          \
    -p 8484:8484                    \
    -v "$PERSIST_DIR":/persist      \
    --env-file "$PROJECT_DIR"/.env  \
    -it                             \
    gristlabs/grist