#!/usr/bin/env bash

SCRIPT_FILE="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_FILE")"
source "$SCRIPT_DIR/activate.sh"

docker run                          \
    -p 8484:8484                    \
    -v "$PERSIST_DIR":/persist      \
    --env-file "$PROJECT_DIR"/.env  \
    -it                             \
    gristlabs/grist